# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/bd/system/ip/system_fft_pl_ps_0_0/system_fft_pl_ps_0_0.xci
# IP: The module: 'system_fft_pl_ps_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: x:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.gen/sources_1/bd/system/ip/system_fft_pl_ps_0_0/system_fft_pl_ps_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fft_pl_ps_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/bd/system/ip/system_fft_pl_ps_0_0/system_fft_pl_ps_0_0.xci
# IP: The module: 'system_fft_pl_ps_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/ip/xfft_0/xfft_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: X:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: x:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.gen/sources_1/bd/system/ip/system_fft_pl_ps_0_0/system_fft_pl_ps_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fft_pl_ps_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
