@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 07 13:03:06 +0300 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_fft_windowed_behav -key {Behavioral:sim_1:Functional:tb_fft_windowed} -tclbatch tb_fft_windowed.tcl -view C:/Users/USER/Documents/baryonic_space/baryonic_space-main/part2/vivado_part2/tb_fft_windowed_behav.wcfg -log simulate.log -testplusarg MEM_DIR=."
call xsim  tb_fft_windowed_behav -key {Behavioral:sim_1:Functional:tb_fft_windowed} -tclbatch tb_fft_windowed.tcl -view C:/Users/USER/Documents/baryonic_space/baryonic_space-main/part2/vivado_part2/tb_fft_windowed_behav.wcfg -log simulate.log -testplusarg MEM_DIR=.
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
