# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_200M_0/system_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_200M_0 || ORIG_REF_NAME==system_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fft_pl_ps_0_0/system_fft_pl_ps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fft_pl_ps_0_0 || ORIG_REF_NAME==system_fft_pl_ps_0_0} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_0_0/system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] -quiet

# IP: bd/system/ip/system_peak_index_pad_const_0/system_peak_index_pad_const_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_peak_index_pad_const_0 || ORIG_REF_NAME==system_peak_index_pad_const_0} -quiet] -quiet

# IP: bd/system/ip/system_peak_index_concat_0/system_peak_index_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_peak_index_concat_0 || ORIG_REF_NAME==system_peak_index_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_imp_auto_pc_0/system_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: x:/part4/vivado_part4_zynq/fft_pl_ps_part4_zynq.gen/sources_1/bd/system/system_ooc.xdc
